global:
  qsname: quickstart-mongodb
  reporting: true
  regions:
    - ap-northeast-1
    - ap-northeast-2
    - ap-south-1
    - ap-southeast-1
    - ap-southeast-2
    - eu-central-1
    - eu-west-1
    - sa-east-1
    - us-east-1
    - us-west-1
    - us-west-2
tests:
  qs_mongod-ap-south-1:
    template_file:  MongoDB-VPC.template
    parameter_input: MongoDB-VPC-ap-south-1.json
    regions:
    - ap-south-1
  qs_mongod-us-east-1:
    template_file:  MongoDB-VPC.template
    parameter_input: MongoDB-VPC-us-east-1.json
    regions:
    - us-east-1
  qs_mongod-us-west-1:
    template_file:  MongoDB-VPC.template
    parameter_input: MongoDB-VPC-us-west-1.json
    regions:
    - us-west-1
  qs_mongod-eu-west-1:
    template_file:  MongoDB-VPC.template
    parameter_input: MongoDB-VPC-eu-west-1.json
    regions:
    - eu-west-1
  qs_mongod-us-west-2:
    template_file:  MongoDB-VPC.template
    parameter_input: MongoDB-VPC-us-west-2.json
    regions:
    - us-west-2
  qs_mongod-sa-east-1:
    template_file:  MongoDB-VPC.template
    parameter_input: MongoDB-VPC-sa-east-1.json
    regions:
    - sa-east-1
  qs_mongod-eu-central-1:
    template_file:  MongoDB-VPC.template
    parameter_input: MongoDB-VPC-eu-central-1.json
    regions:
    - eu-central-1
  qs_mongod-ap-northeast-1:
    template_file:  MongoDB-VPC.template
    parameter_input: MongoDB-VPC-ap-northeast-1.json
    regions:
    - ap-northeast-1
  qs_mongod-ap-northeast-2:
    template_file:  MongoDB-VPC.template
    parameter_input: MongoDB-VPC-ap-northeast-2.json
    regions:
    - ap-northeast-2
  qs_mongod-ap-southeast-1:
    template_file:  MongoDB-VPC.template
    parameter_input: MongoDB-VPC-ap-southeast-1.json
    regions:
    - ap-southeast-1
  qs_mongod-ap-southeast-2:
    template_file:  MongoDB-VPC.template
    parameter_input: MongoDB-VPC-ap-southeast-2.json
    regions:
    - ap-southeast-2
